"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {Activity,AlertCircle,ArrowRight,Building2,Check,ChevronDown,ChevronRight,Clipboard,Database,FileClock,HeartPulse,History,LayoutDashboard,Network,RefreshCw,Server,ShieldCheck,TriangleAlert,X} from "lucide-react";
import {loadRC2Workspace,RC2ApiError,simulateHospitalPolicyChange} from "../../lib/rc2/client";
import type {BinaryValue,LedgerStatus,RC2WorkspaceData,ResponseVersion,TamperResult,VerificationCheck,VerificationStatus} from "../../lib/rc2/types";

const organizations:Record<string,{name:string;kind:string}>={
  "HOSPITAL-A":{name:"Hospital A",kind:"Healthcare provider"},
  "PAYER-B":{name:"Payer B",kind:"Health plan"},
  "STAFFING-AGENCY-C":{name:"Staffing Agency C",kind:"Staffing organization"},
};
const stateLabels:Record<string,string>={RECEIVED:"Received",UNDER_REVIEW:"Under review",DECIDED:"Decided",ACTION_COMPLETED:"Action completed"};
const steps=["RECEIVED","UNDER_REVIEW","DECIDED","ACTION_COMPLETED"];
type Mode="operations"|"technical";

export function AuthorityWorkspace(){
  const[data,setData]=useState<RC2WorkspaceData|null>(null);
  const[error,setError]=useState<unknown>(null);
  const[mode,setMode]=useState<Mode>("operations");
  const[selected,setSelected]=useState("HOSPITAL-A");
  const[refreshing,setRefreshing]=useState(true);
  const[tamper,setTamper]=useState<TamperResult|null>(null);
  const reload=useCallback(async()=>{setRefreshing(true);setError(null);try{setData(await loadRC2Workspace())}catch(value){setError(value)}finally{setRefreshing(false)}},[]);
  useEffect(()=>{let live=true;loadRC2Workspace().then(value=>{if(live){setData(value);setRefreshing(false)}}).catch(value=>{if(live){setError(value);setRefreshing(false)}});return()=>{live=false}},[]);
  const nav:Array<[string,typeof LayoutDashboard]>=mode==="operations"?[["Overview",LayoutDashboard],["Authority events",FileClock],["Responses",Building2],["Verification",ShieldCheck]]:[["Network",Network],["Ledger activity",Activity],["Evidence",Database],["Integrity demo",ShieldCheck]];
  return <div className="authority-app">
    <aside className="authority-sidebar">
      <div className="authority-brand"><span><HeartPulse/></span><div><b>HealthTrust</b><small>Professional Authority Response</small></div></div>
      <nav aria-label={mode==="operations"?"Operations navigation":"Technical navigation"}>{nav.map(([item,Icon],index)=><a key={item} href={`#${item.toLowerCase().replaceAll(" ","-")}`} className={index===0?"active":""}><Icon/>{item}</a>)}</nav>
      <div className="authority-side-note"><ShieldCheck/><div><b>Shared evidence</b><small>Independent decisions</small></div></div>
    </aside>
    <main className="authority-main">
      <header className="authority-topbar"><div><span>HealthTrust RC2</span><b>{data?.event.ID??"Professional authority event"}</b></div><div className="view-switch" aria-label="Presentation mode. This is not an access-control switch."><span>Presentation</span><div role="group" aria-label="Presentation mode"><button aria-pressed={mode==="operations"} onClick={()=>setMode("operations")}>Operations</button><button aria-pressed={mode==="technical"} onClick={()=>setMode("technical")}>Technical</button></div></div></header>
      <div className="demo-disclaimer"><TriangleAlert/><span><b>Demonstration data</b> — synthetic scenario, not for clinical or compliance use.</span></div>
      {!data&&!error&&<LoadingState/>}
      {error!==null&&<ErrorState error={error} retry={reload}/>}
      {data&&mode==="operations"&&<OperationsView data={data} selected={selected} select={setSelected} showTechnical={()=>setMode("technical")}/>}
      {data&&mode==="technical"&&<TechnicalView data={data} selected={selected} select={setSelected} reload={reload} refreshing={refreshing} tamper={tamper} setTamper={setTamper}/>}
    </main>
  </div>
}

function OperationsView({data,selected,select,showTechnical}:{data:RC2WorkspaceData;selected:string;select:(id:string)=>void;showTechnical:()=>void}){
  const attention=data.bundle.status==="VERIFIED"?0:data.bundle.responses.filter(item=>item.result.status!=="VERIFIED").length||1;
  return <div className="authority-content" id="overview">
    <div className="authority-heading"><div><span className="authority-kicker">Operations overview</span><h1>One event. Three independent responses.</h1><p>Each organization received the same professional authority event and applied its own policy.</p></div><StatusPill status={data.bundle.status}/></div>
    <section className="authority-metrics" aria-label="Event summary"><Metric label="Active event" value="1" detail={human(data.event.EventType)}/><Metric label="Organizations responded" value={String(data.responses.length)} detail="Independent responses"/><Metric label="Needs attention" value={String(attention)} detail={attention?"Review evidence":"Nothing flagged"}/><Metric label="Evidence status" value={verificationLabel(data.bundle.status)} detail="Current vs recorded" status={data.bundle.status}/></section>
    <section className="event-spotlight" id="authority-events"><div className="event-ribbon"><span>Professional Authority Event</span><StatusPill status={data.bundle.authority.status}/></div><div className="event-body"><div className="event-type"><span>Event type</span><strong>{human(data.event.EventType)}</strong><small>{historyLabel(data.event.AssertionKind)}</small></div><dl><Detail label="Professional" value={data.event.SubjectID}/><Detail label="Authority" value={data.event.AuthorityID}/><Detail label="Effective" value={formatDate(data.event.EffectiveTime)}/><Detail label="Response series" value={data.event.SeriesID}/></dl></div><details className="event-history"><summary><History/> Event history <ChevronDown/></summary><div><span>{historyLabel(data.event.AssertionKind)}</span><b>{data.event.ID}</b><small>{formatDate(data.event.EffectiveTime)} · current head {data.event.CurrentHead}</small></div></details><a href="#responses" className="text-action">View response activity <ChevronRight/></a></section>
    <section className="response-section" id="responses"><div className="section-heading"><div><span className="authority-kicker">Independent decisions</span><h2>Organizational response activity</h2></div><p>Select a response to inspect its actual four-step lifecycle.</p></div>{data.responses.length===0&&<div className="authority-error" role="status"><Building2/><div><h2>No organization responses yet</h2><p>Responses will appear here after organizations receive the event.</p></div></div>}<div className="response-grid">{data.responses.map(response=><ResponseCard key={response.OrganizationID} response={response} status={statusFor(data,response.OrganizationID)} selected={selected===response.OrganizationID} onSelect={()=>select(response.OrganizationID)} history={data.histories[response.OrganizationID]??[]}/>)}</div></section>
    <section className={`operations-verification ${data.bundle.status.toLowerCase()}`} id="verification"><div><ShieldCheck/><span><b>{verificationLabel(data.bundle.status)}</b><small>{verificationCopy(data.bundle.status)}</small></span></div><button className="quiet-button" onClick={showTechnical}>Technical details <ChevronRight/></button></section>
  </div>
}

function ResponseCard({response,status,selected,onSelect,history}:{response:ResponseVersion;status:VerificationStatus;selected:boolean;onSelect:()=>void;history:ResponseVersion[]}){return <article className={`response-card ${selected?"selected":""}`}><button className="response-card-button" onClick={onSelect} aria-expanded={selected}><span className="organization-icon"><Building2/></span><span><small>{organizations[response.OrganizationID]?.kind??"Responder"}</small><strong>{organizations[response.OrganizationID]?.name??response.OrganizationID}</strong></span><ChevronRight/></button><div className="response-outcome"><span>{stateLabels[response.State]??human(response.State)}</span><strong>{response.actionPresentation?.label??(response.State==="ACTION_COMPLETED"?"Action completed":"Outcome not available")}</strong>{response.actionPresentation?.demoOnly&&<small>Synthetic demonstration outcome</small>}</div><StatusPill status={status}/>{selected&&<ResponseTimeline history={history}/>}</article>}
function ResponseTimeline({history}:{history:ResponseVersion[]}){return <ol className="response-timeline" aria-label="Response lifecycle">{steps.map((step,index)=>{const item=history.find(value=>value.State===step);return <li key={step} className={item?"complete":""}><span>{item?<Check/>:index+1}</span><div><b>{stateLabels[step]}</b>{item&&<small>{formatDate(item.CreatedAt)}</small>}</div></li>})}</ol>}

function TechnicalView({data,selected,select,reload,refreshing,tamper,setTamper}:{data:RC2WorkspaceData;selected:string;select:(id:string)=>void;reload:()=>Promise<void>;refreshing:boolean;tamper:TamperResult|null;setTamper:(value:TamperResult)=>void}){
  const entries=useMemo(()=>[...Object.values(data.histories).flat()].sort((a,b)=>new Date(a.CreatedAt).valueOf()-new Date(b.CreatedAt).valueOf()),[data.histories]);
  return <div className="authority-content technical-content" id="network">
    <div className="authority-heading"><div><span className="authority-kicker">Technical evidence</span><h1>Evidence anchored across a permissioned network.</h1><p>Application views are read from the RC2 API; the browser never connects directly to validator RPC endpoints.</p></div><button className="quiet-button" onClick={()=>void reload()} disabled={refreshing}><RefreshCw className={refreshing?"spin":""}/> Refresh evidence</button></div>
    <section className="technical-section"><SectionTitle eyebrow="Configured topology" title="Three-validator Besu consortium" note="Static deployment configuration — not live peer health or performance telemetry."/><div className="network-map"><TopologyNode title="Hospital validator" detail="Besu · QBFT validator"/><span><ArrowRight/><small>shared ledger</small></span><TopologyNode title="Payer validator" detail="Besu · QBFT validator"/><span><ArrowRight/><small>shared ledger</small></span><TopologyNode title="Staffing validator" detail="Besu · QBFT validator"/></div></section>
    <section className="technical-section" id="ledger-activity"><SectionTitle eyebrow="Ledger activity" title="Authority event to response evidence" note={`${entries.length+1} confirmed application submissions shown from the current API state.`}/><div className="flow-strip"><FlowStep label="Authority event" value={data.event.ID}/><ArrowRight/><FlowStep label="Shared series" value={data.event.SeriesID}/><ArrowRight/><FlowStep label="Independent responses" value={`${data.responses.length} organizations`}/><ArrowRight/><FlowStep label="Verification" value={data.bundle.status}/></div><div className="ledger-table" role="region" aria-label="Ledger activity"><table><thead><tr><th>Record</th><th>Organization</th><th>State</th><th>Block</th><th>Transaction</th></tr></thead><tbody><LedgerRow id={data.event.ID} organization="Authority" state={data.event.Ledger.state} ledger={data.event.Ledger}/>{entries.map(item=><LedgerRow key={item.ID} id={item.ID} organization={organizations[item.OrganizationID]?.name??item.OrganizationID} state={item.State} ledger={item.Ledger}/>)}</tbody></table></div></section>
    <section className="technical-section" id="evidence"><SectionTitle eyebrow="Evidence comparison" title="Current evidence vs recorded commitments" note="A match means the current canonical evidence equals the value previously recorded on the ledger."/><div className="evidence-tabs" role="tablist" aria-label="Organization evidence">{data.responses.map(response=><button key={response.OrganizationID} role="tab" aria-selected={selected===response.OrganizationID} onClick={()=>select(response.OrganizationID)}>{organizations[response.OrganizationID]?.name}</button>)}</div><EvidencePanel data={data} organization={selected}/></section>
    <IntegrityDemo data={data} reload={reload} tamper={tamper} setTamper={setTamper}/>
  </div>
}

function EvidencePanel({data,organization}:{data:RC2WorkspaceData;organization:string}){
  const result=data.verifications[organization];
  const policy=latestPolicyCheck(result?.checks??[]);
  return <div className="evidence-panel"><div><span>Organization</span><b>{organizations[organization]?.name??organization}</b><small>{organizations[organization]?.kind}</small></div><EvidenceValue label="Current canonical policy evidence" value={policy?.expected}/><EvidenceValue label="Previously recorded policy evidence" value={policy?.observed}/><div><span>Comparison result</span><StatusPill status={policy?.status??result?.status??"INDETERMINATE"}/><small>PolicyV1 canonical commitment</small></div></div>
}

function IntegrityDemo({data,reload,tamper,setTamper}:{data:RC2WorkspaceData;reload:()=>Promise<void>;tamper:TamperResult|null;setTamper:(value:TamperResult)=>void}){
  const[open,setOpen]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState<unknown>(null);
  const hospital=statusFor(data,"HOSPITAL-A"),alreadyFailed=hospital==="FAILED";
  async function confirm(){setPending(true);setError(null);try{const result=await simulateHospitalPolicyChange();setTamper(result);setOpen(false);await reload()}catch(value){setError(value)}finally{setPending(false)}}
  return <section className="integrity-demo technical-section" id="integrity-demo"><SectionTitle eyebrow="Controlled integrity demonstration" title="Show that changed evidence is detected" note="This local-only demo changes one synthetic Hospital A policy row. It does not alter the ledger."/><div className="integrity-layout"><div className="integrity-copy"><div className="integrity-warning"><TriangleAlert/><p><b>Demonstration only.</b> The action is fixed to the synthetic Hospital A policy and is disabled unless the backend demo flag is enabled.</p></div><h3>{alreadyFailed?"A difference has been detected":"Evidence currently matches"}</h3><p>{verificationCopy(hospital)}</p><button className="danger-button" onClick={()=>setOpen(true)} disabled={alreadyFailed}>Simulate local policy change</button>{alreadyFailed&&<small>Refresh-safe: the synthetic database change remains visible until the disposable demo environment is reset.</small>}{tamper?.ledgerUnchanged&&<p className="unchanged"><ShieldCheck/> Recorded ledger evidence remained unchanged.</p>}</div><div className="integrity-statuses">{data.responses.map(response=><div key={response.OrganizationID}><span>{organizations[response.OrganizationID]?.name}</span><StatusPill status={statusFor(data,response.OrganizationID)}/></div>)}</div></div>{open&&<ConfirmDialog pending={pending} error={error} cancel={()=>{setOpen(false);setError(null)}} confirm={confirm}/>}</section>
}

function ConfirmDialog({pending,error,cancel,confirm}:{pending:boolean;error:unknown;cancel:()=>void;confirm:()=>void}){
  const dialog=useRef<HTMLDivElement>(null),cancelButton=useRef<HTMLButtonElement>(null),returnFocus=useRef<HTMLElement|null>(null);
  useEffect(()=>{returnFocus.current=document.activeElement as HTMLElement;cancelButton.current?.focus();const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!pending)cancel();if(event.key==="Tab"&&dialog.current){const controls=[...dialog.current.querySelectorAll<HTMLElement>('button:not([disabled])')];if(!controls.length)return;const first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};document.addEventListener("keydown",onKey);return()=>{document.removeEventListener("keydown",onKey);returnFocus.current?.focus()}},[cancel,pending]);
  return <div className="dialog-backdrop"><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="integrity-dialog-title" ref={dialog}><button className="dialog-close" aria-label="Close" onClick={cancel} disabled={pending}><X/></button><span className="dialog-icon"><AlertCircle/></span><h2 id="integrity-dialog-title">Simulate a local evidence change?</h2><p>This deliberately changes the synthetic Hospital A policy in PostgreSQL. The recorded blockchain commitment will not be changed.</p><div className="dialog-facts"><span>Target</span><b>HOSPITAL_A_POLICY</b><span>Scope</span><b>Local demonstration data only</b></div>{error!==null&&<InlineError error={error}/>}<div className="dialog-actions"><button className="quiet-button" ref={cancelButton} onClick={cancel} disabled={pending}>Cancel</button><button className="danger-button" onClick={confirm} disabled={pending}>{pending?"Applying controlled change…":"Confirm simulation"}</button></div></div></div>
}

function LedgerRow({id,organization,state,ledger}:{id:string;organization:string;state:string;ledger:LedgerStatus}){return <tr><td><Identifier value={id}/></td><td>{organization}</td><td><span className="ledger-state"><span/>{human(state)}</span></td><td>{ledger.blockNumber??"—"}</td><td><Identifier value={toHex(ledger.transactionHash)}/></td></tr>}
function Identifier({value}:{value?:string}){const display=value?shorten(value):"Unavailable";return <span className="identifier" title={value}><code>{display}</code>{value&&<button aria-label={`Copy ${value}`} onClick={()=>void navigator.clipboard?.writeText(value)}><Clipboard/></button>}</span>}
function EvidenceValue({label,value}:{label:string;value?:string}){return <div><span>{label}</span><Identifier value={value}/><small>{value?"SHA-256 commitment":"Not available"}</small></div>}
function TopologyNode({title,detail}:{title:string;detail:string}){return <article><span><Server/></span><b>{title}</b><small>{detail}</small></article>}
function FlowStep({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
function SectionTitle({eyebrow,title,note}:{eyebrow:string;title:string;note:string}){return <div className="section-heading"><div><span className="authority-kicker">{eyebrow}</span><h2>{title}</h2></div><p>{note}</p></div>}
function Detail({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function StatusPill({status}:{status:VerificationStatus}){return <span className={`status-pill ${status.toLowerCase()}`}><span/>{verificationLabel(status)}</span>}
function Metric({label,value,detail,status}:{label:string;value:string;detail:string;status?:VerificationStatus}){return <article><span>{label}</span><strong className={status?status.toLowerCase():""}>{value}</strong><small>{detail}</small></article>}
function LoadingState(){return <div className="authority-loading" aria-live="polite"><div/><div/><div/><span>Loading authoritative event evidence…</span></div>}
function ErrorState({error,retry}:{error:unknown;retry:()=>void}){const detail=errorMessage(error);return <section className="authority-error" role="alert"><TriangleAlert/><div><h1>{detail.title}</h1><p>{detail.message}</p><button className="quiet-button" onClick={retry}><RefreshCw/> Try again</button></div></section>}
function InlineError({error}:{error:unknown}){return <div className="inline-error" role="alert">{errorMessage(error).message}</div>}
function errorMessage(error:unknown){if(error instanceof RC2ApiError){if(error.status===403)return{title:"Demonstration disabled",message:"The backend has not enabled the controlled integrity demonstration."};if(error.status===404)return{title:"Evidence not found",message:"The requested synthetic event or evidence record was not found."};if(error.status===409)return{title:"Simulation already applied",message:"The controlled evidence change has already been applied."};if(error.status===400)return{title:"Request not accepted",message:"The backend rejected the fixed demonstration request."};if(error.status===503)return{title:"Verification unavailable",message:"HealthTrust could not complete this evidence check right now."}}return{title:"Authority service unavailable",message:"The RC2 demo runtime could not be reached. Start the local demonstration environment and try again."}}
function statusFor(data:RC2WorkspaceData,id:string):VerificationStatus{return data.bundle.responses.find(value=>value.organizationId===id)?.result.status??data.verifications[id]?.status??"INDETERMINATE"}
function latestPolicyCheck(checks:VerificationCheck[]){return [...checks].reverse().find(check=>check.type==="CANONICAL_COMMITMENT"&&check.objectId.endsWith(":policy"))}
function verificationLabel(status:VerificationStatus){return status==="VERIFIED"?"Evidence verified":status==="FAILED"?"Evidence no longer matches":"Verification unavailable"}
function verificationCopy(status:VerificationStatus){return status==="VERIFIED"?"The current evidence matches the previously recorded audit evidence.":status==="FAILED"?"The current record differs from evidence that was previously recorded.":"HealthTrust could not complete this evidence check right now."}
function historyLabel(kind:string){return({ORIGINAL:"Original notice",CORRECTION:"Correction",SUPERSESSION:"Superseded notice",REINSTATEMENT:"Exclusion lifted"}as Record<string,string>)[kind]??human(kind)}
function human(value:string){return value.toLowerCase().replaceAll("_"," ").replace(/^./,letter=>letter.toUpperCase())}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.valueOf())?"Time unavailable":new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(date)}
function shorten(value:string){return value.length>23?`${value.slice(0,12)}…${value.slice(-8)}`:value}
function toHex(value?:BinaryValue){if(value===undefined)return undefined;if(Array.isArray(value))return `0x${value.map(byte=>byte.toString(16).padStart(2,"0")).join("")}`;if(value.startsWith("0x"))return value;try{return `0x${Array.from(atob(value),character=>character.charCodeAt(0).toString(16).padStart(2,"0")).join("")}`}catch{return value}}
