"use client";
import Link from "next/link";
import {motion,useReducedMotion} from "framer-motion";
import {AlertTriangle,ArrowRight,Building2,CheckCircle2,Clock3,Database,FileCheck2,FileText,Fingerprint,Info,ShieldCheck,UsersRound} from "lucide-react";
import {useEffect,useRef,useState} from "react";
import {EvidenceRail,NarrativeHeader,StageToolbar,useActiveNarrativeStep} from "./demo-story";
import {loadRC2Workspace} from "../lib/rc2/client";
import type{RC2WorkspaceData,ResponseVersion,VerificationStatus}from"../lib/rc2/types";

const scenes=[
 {title:"Authority event received",body:"A synthetic professional-authority event becomes available to authorized organizations.",icon:FileText,testid:"authority-story-1"},
 {title:"Three organizations observe the event",body:"Hospital A, Payer B, and Staffing Agency C receive the same event.",icon:UsersRound,testid:"authority-story-2"},
 {title:"Independent organizational responses",body:"Each organization evaluates the event and takes its own operational action.",icon:Building2,testid:"authority-story-3",callout:"Shared evidence does not mean shared decisions. Each organization remains operationally independent."},
 {title:"Response lifecycle",body:"Each response progresses through received, under review, decided, and action completed states.",icon:Clock3,testid:"authority-story-4"},
 {title:"Evidence recorded",body:"Safe commitments and transaction references are recorded as verifiable evidence.",icon:Database,testid:"authority-story-5"},
 {title:"Verification succeeds",body:"Current canonical evidence matches the evidence previously recorded for each organization.",icon:ShieldCheck,testid:"authority-story-6"},
 {title:"Controlled local change",body:"The presentation changes only Hospital A’s local policy evidence; recorded evidence stays fixed.",icon:AlertTriangle,testid:"authority-story-7"},
 {title:"Mismatch detected",body:"Hospital A differs from recorded evidence while Payer B and Staffing Agency C remain verified.",icon:Fingerprint,testid:"authority-story-8",callout:"The local record changed. Previously recorded evidence did not. This makes inconsistency detectable—not preventable."},
];
const organizationNames:Record<string,string>={"HOSPITAL-A":"Hospital A","PAYER-B":"Payer B","STAFFING-AGENCY-C":"Staffing Agency C"};
const ids=["HOSPITAL-A","PAYER-B","STAFFING-AGENCY-C"];

export function AuthorityStory(){
 const storyRef=useRef<HTMLElement|null>(null),timelineRef=useRef<HTMLDivElement|null>(null),stepRefs=useRef<(HTMLElement|null)[]>([]),reduce=useReducedMotion();
 const[active,selectActive]=useActiveNarrativeStep(stepRefs,timelineRef,scenes.length),[replayKey,setReplayKey]=useState(0),[data,setData]=useState<RC2WorkspaceData|null>(null),[error,setError]=useState(false);
 useEffect(()=>{loadRC2Workspace().then(setData).catch(()=>setError(true))},[]);
 const goTo=(index:number)=>{const node=stepRefs.current[index],timeline=timelineRef.current;if(!node||!timeline)return;selectActive(index);const scrollable=timeline.scrollHeight>timeline.clientHeight+1&&getComputedStyle(timeline).overflowY!=="visible";if(scrollable)timeline.scrollTo({top:node.offsetTop-(timeline.clientHeight-node.offsetHeight)/2,behavior:reduce?"auto":"smooth"});else node.scrollIntoView({behavior:reduce?"auto":"smooth",block:"center",inline:"nearest"})};
 const final=active===7;
 return <main className="narrative-page rc2-story-page"><NarrativeHeader active="rc2"/><header className="narrative-hero"><span className="narrative-eyebrow">RC2 <i/> DEMO</span><h1>One event. Three organizations. <em>Independent responses.</em></h1><p>A single professional-authority event is shared as verifiable evidence while each organization retains independent decision-making and operational control.</p></header>{error&&<p className="narrative-api-note" role="status">Live RC2 presentation data is unavailable. No verification outcome is being inferred.</p>}<section ref={storyRef} className="narrative-story" data-testid="authority-scroll-story"><aside className="narrative-stage-wrap"><RC2Stage replayKey={replayKey} active={active} reduced={!!reduce} data={data} onReplay={()=>setReplayKey(value=>value+1)}/></aside><div ref={timelineRef} className="narrative-timeline" aria-label="RC2 evidence workflow steps">{scenes.map((scene,index)=><article key={scene.title} ref={node=>{stepRefs.current[index]=node}} className={`narrative-step ${index===active?"is-active":""} ${index<active?"is-complete":""}`} data-testid={scene.testid} data-active={index===active}><button type="button" onClick={()=>goTo(index)} aria-label={`Show step ${index+1}: ${scene.title}`}><span className="narrative-step-node">{index<active?<CheckCircle2/>:null}</span><span className="narrative-step-number">{String(index+1).padStart(2,"0")}</span><span className="narrative-step-icon"><scene.icon/></span><span className="narrative-step-copy"><b>{scene.title}</b><small>{scene.body}</small></span></button>{scene.callout&&<p className="narrative-callout"><Info/>{scene.callout}</p>}</article>)}{final?<Link className="narrative-continue" href="/authority">Open RC2 workspace <ArrowRight/></Link>:<button className="narrative-continue" type="button" onClick={()=>goTo(active+1)}>Continue to next step <ArrowRight/></button>}</div></section></main>
}

function RC2Stage({active,reduced,data,onReplay,replayKey}:{active:number;reduced:boolean;data:RC2WorkspaceData|null;onReplay:()=>void;replayKey:number}){
 const revealOrganizations=active>=1,revealOutcomes=active>=2,revealLifecycle=active>=3,revealEvidence=active>=4,verified=active>=5,changed=active>=6,mismatch=active>=7,event=data?.event;
 return <motion.div className="narrative-stage rc2-stage" data-step={active+1} data-reduced={reduced} aria-label={`RC2 narrative state: ${scenes[active].title}`} initial={reduced?false:{opacity:.96}} animate={{opacity:1}}><StageToolbar step={active+1} title={scenes[active].title} onReplay={onReplay}/><motion.i key={replayKey} className="narrative-replay-sweep" initial={reduced?false:{opacity:.28}} animate={{opacity:0}} transition={{duration:.55}}/><div className="rc2-authority-event"><span><FileText/></span><div><b>Authority Event</b><small>{event?`${event.EventType} · ${event.SubjectID} · ${event.AuthorityID}`:"Loading authoritative event…"}</small><em>Shared with authorized organizations</em></div></div><svg className="rc2-story-connectors" viewBox="0 0 900 510" aria-hidden><path className={revealOrganizations?"is-visible is-active":""} d="M450 135 V170 H150 V210 M450 170 V210 M450 170 H750 V210"/><path className={revealLifecycle?"is-visible is-active":""} d="M150 305 V395 M450 305 V395 M750 305 V395"/><path className={revealEvidence?"is-visible is-active":""} d="M150 395 V435 H750 M450 395 V455 M750 395 V435"/><path className={changed?"is-visible is-change":""} d="M150 395 V455"/></svg><div className={`rc2-organization-grid ${revealOrganizations?"is-visible":""}`} aria-hidden={!revealOrganizations}>{ids.map((id,index)=>{const response=data?.responses.find(item=>item.OrganizationID===id);return <RC2Organization key={id} id={id} index={index} response={response} status={verificationStatus(data,id)} revealOutcome={revealOutcomes} revealLifecycle={revealLifecycle} verified={verified} changed={changed&&index===0} mismatch={mismatch&&index===0}/>})}</div>{verified&&<div className={`rc2-verification-summary ${mismatch?"is-mismatch":""}`}><ShieldCheck/><span>{mismatch?"Hospital A mismatch · recorded evidence unchanged":"Current evidence matches recorded evidence"}</span></div>}{revealEvidence&&<motion.div className="rc2-evidence-zone" initial={reduced?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.35}}><EvidenceRail title="Recorded Evidence" subtitle="Safe commitments · independent response history" label="Operational details remain off-chain" count={Math.min(5,Math.max(1,active-2))} active/></motion.div>}</motion.div>
}

function verificationStatus(data:RC2WorkspaceData|null,id:string):VerificationStatus|undefined{return data?.verifications[id]?.status??data?.bundle.responses.find(item=>item.organizationId===id)?.result.status}
function RC2Organization({id,index,response,status,revealOutcome,revealLifecycle,verified,changed,mismatch}:{id:string;index:number;response?:ResponseVersion;status?:VerificationStatus;revealOutcome:boolean;revealLifecycle:boolean;verified:boolean;changed:boolean;mismatch:boolean}){
 const outcome=response?.actionPresentation?.label??"Response data unavailable",displayStatus=mismatch?"FAILED":verified?(status??"INDETERMINATE"):undefined;
 return <div className={`rc2-organization-column ${changed?"is-changed":""} ${mismatch?"is-mismatch":""}`}><article className="rc2-organization-card"><span>{index===0?<Building2/>:index===1?<ShieldCheck/>:<UsersRound/>}</span><div><b>{organizationNames[id]}</b><small>{revealOutcome?outcome:"Observing shared event"}</small>{displayStatus&&<strong className={displayStatus.toLowerCase()}>{displayStatus}</strong>}</div></article><article className={`rc2-local-response ${revealLifecycle?"is-visible":""}`} aria-hidden={!revealLifecycle}><span><FileCheck2/></span><div><b>Local response</b><small>{changed&&index===0?"Synthetic local evidence changed":outcome}</small><em><CheckCircle2/>{response?.State??"Action completed"}</em></div></article></div>
}
