"use client";
import Link from "next/link";
import {motion,useReducedMotion} from "framer-motion";
import {ArrowRight,CheckCircle2,Database,FileHeart,Fingerprint,HeartHandshake,Hospital,Info,KeyRound,Link2,LockKeyhole,RotateCcw,Send,ShieldCheck,UserRound,XCircle} from "lucide-react";
import {useEffect,useRef,useState} from "react";

const scenes=[
 {title:"Clinical record created",body:"Hospital A creates the source clinical record. The record remains at Hospital A.",icon:FileHeart,testid:"story-record"},
 {title:"Referral / access request",body:"Hospital B requests access to the patient’s information for continuing care.",icon:Send,testid:"story-referral"},
 {title:"Patient authorization required",body:"The request pauses until Patient P reviews and grants scoped authorization.",icon:LockKeyhole,testid:"story-authorization",callout:"No clinical information is shared without the patient’s authorization."},
 {title:"Patient grants consent",body:"Patient P approves the specific cross-hospital request and activates the authorized path.",icon:HeartHandshake,testid:"story-consent"},
 {title:"Secure retrieval",body:"Hospital B receives authorized viewing access while Hospital A remains the source organization.",icon:Database,testid:"story-retrieval",callout:"Authorization permits access; ownership of the source record does not move."},
 {title:"Integrity verification",body:"The current record commitment is compared with the previously recorded integrity evidence.",icon:ShieldCheck,testid:"story-integrity",callout:"Integrity evidence can reveal inconsistency; it does not prove clinical content is true."},
 {title:"Audit history",body:"Signed referral, authorization, access, and verification events remain available as history.",icon:Fingerprint,testid:"story-audit"},
 {title:"Consent revoked",body:"Patient P closes the authorization path. Previously recorded history remains intact.",icon:XCircle,testid:"story-revocation"},
 {title:"Access denied again",body:"A later access attempt is denied because authorization is no longer active.",icon:LockKeyhole,testid:"story-denied",callout:"Revocation closes future access without erasing prior audit evidence."},
];

export function DemoStory(){
 const storyRef=useRef<HTMLElement|null>(null),timelineRef=useRef<HTMLDivElement|null>(null),stepRefs=useRef<(HTMLElement|null)[]>([]),reduce=useReducedMotion();
 const[active,selectActive]=useActiveNarrativeStep(stepRefs,timelineRef,scenes.length),[replayKey,setReplayKey]=useState(0);
 const goTo=(index:number)=>{const node=stepRefs.current[index],timeline=timelineRef.current;if(!node||!timeline)return;selectActive(index);const scrollable=timeline.scrollHeight>timeline.clientHeight+1&&getComputedStyle(timeline).overflowY!=="visible";if(scrollable)timeline.scrollTo({top:node.offsetTop-(timeline.clientHeight-node.offsetHeight)/2,behavior:reduce?"auto":"smooth"});else node.scrollIntoView({behavior:reduce?"auto":"smooth",block:"center",inline:"nearest"})};
 const final=active===scenes.length-1;
 return <main className="narrative-page rc1-story-page"><NarrativeHeader active="rc1"/><header className="narrative-hero"><span className="narrative-eyebrow">RC1 <i/> DEMO</span><h1>One record. Two hospitals. <em>Patient-controlled trust.</em></h1><p>A patient controls cross-hospital access to clinical information while the source organization retains the record and every exchange remains auditable.</p></header><section ref={storyRef} className="narrative-story" data-testid="scroll-story"><aside className="narrative-stage-wrap"><RC1Stage replayKey={replayKey} active={active} reduced={!!reduce} onReplay={()=>setReplayKey(value=>value+1)}/></aside><div ref={timelineRef} className="narrative-timeline" aria-label="RC1 workflow steps">{scenes.map((scene,index)=><article key={scene.title} ref={node=>{stepRefs.current[index]=node}} className={`narrative-step ${index===active?"is-active":""} ${index<active?"is-complete":""}`} data-testid={scene.testid} data-active={index===active}><button type="button" onClick={()=>goTo(index)} aria-label={`Show step ${index+1}: ${scene.title}`}><span className="narrative-step-node">{index<active?<CheckCircle2/>:null}</span><span className="narrative-step-number">{String(index+1).padStart(2,"0")}</span><span className="narrative-step-icon"><scene.icon/></span><span className="narrative-step-copy"><b>{scene.title}</b><small>{scene.body}</small></span></button>{scene.callout&&<p className="narrative-callout"><Info/>{scene.callout}</p>}</article>)}{final?<Link className="narrative-continue" href="/app">Explore RC1 application <ArrowRight/></Link>:<button className="narrative-continue" type="button" onClick={()=>goTo(active+1)}>Continue to next step <ArrowRight/></button>}</div></section></main>
}

export function NarrativeHeader({active}:{active:"rc1"|"rc2"}){return <nav className="narrative-nav" aria-label="Narrative navigation"><Link href="/" className="narrative-brand"><b>Health<span>Trust</span></b><small>Secure exchange. Informed care.</small></Link><div className="narrative-nav-links"><Link href="/">Overview</Link><Link href="/#evolution">Evolution</Link><Link href="/demo" aria-current={active==="rc1"?"page":undefined}>RC1</Link><Link href="/authority/demo" aria-current={active==="rc2"?"page":undefined}>RC2</Link><Link href="/#comparison">Engineering</Link></div><Link className="narrative-home" href="/">Back to home <ArrowRight/></Link></nav>}
export function useActiveNarrativeStep(refs:React.MutableRefObject<(HTMLElement|null)[]>,containerRef:React.MutableRefObject<HTMLDivElement|null>,count:number){const[active,setActive]=useState(0);useEffect(()=>{let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const container=containerRef.current;if(!container)return;const scrollable=container.scrollHeight>container.clientHeight+1&&getComputedStyle(container).overflowY!=="visible";if(scrollable&&container.scrollTop<=1){setActive(0);return}if(scrollable&&container.scrollTop>=container.scrollHeight-container.clientHeight-1){setActive(count-1);return}const bounds=container.getBoundingClientRect(),center=scrollable?bounds.top+bounds.height/2:window.innerHeight/2;let closest=0,distance=Number.POSITIVE_INFINITY;refs.current.forEach((node,index)=>{if(!node)return;const rect=node.getBoundingClientRect(),next=Math.abs(rect.top+rect.height/2-center);if(next<distance){distance=next;closest=index}});setActive(Math.min(count-1,closest))})};update();const container=containerRef.current;container?.addEventListener("scroll",update,{passive:true});window.addEventListener("scroll",update,{passive:true});window.addEventListener("resize",update);return()=>{cancelAnimationFrame(frame);container?.removeEventListener("scroll",update);window.removeEventListener("scroll",update);window.removeEventListener("resize",update)}},[containerRef,count,refs]);return[active,setActive]as const}

function RC1Stage({active,reduced,onReplay,replayKey}:{active:number;reduced:boolean;onReplay:()=>void;replayKey:number}){
 const required=active===2,approved=active>=3&&active<7,revoked=active>=7,denied=active>=8,evidenceCount=Math.min(5,Math.max(1,active-1));
 return <motion.div className="narrative-stage rc1-stage" data-step={active+1} data-reduced={reduced} aria-label={`RC1 workflow state: ${scenes[active].title}`} initial={reduced?false:{opacity:.96}} animate={{opacity:1}}><StageToolbar step={active+1} title={scenes[active].title} onReplay={onReplay}/><motion.i key={replayKey} className="narrative-replay-sweep" initial={reduced?false:{opacity:.28}} animate={{opacity:0}} transition={{duration:.55}}/><svg className="rc1-story-connectors" viewBox="0 0 900 470" aria-hidden><path className={active>=1?"is-active":""} d="M250 160 H650"/><path className={active>=2&&!revoked?"is-active":""} d="M240 188 Q330 330 430 330"/><path className={approved?"is-active":revoked?"is-closed":""} d="M660 188 Q570 330 470 330"/></svg><OrganizationCard className="rc1-hospital-a" name="Hospital A" descriptor="Source of record"/><OrganizationCard className="rc1-hospital-b" name="Hospital B" descriptor={denied?"Access denied":active>=1?"Requesting access":"Receiving organization"}/><motion.div className="rc1-record-card" initial={reduced?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.4}}><span><FileHeart/></span><div><b>Clinical record</b><small>Owned by Hospital A</small><em><LockKeyhole/>Stored off-chain</em></div></motion.div><motion.div className={`rc1-request ${active>=1?"is-visible":""} ${required?"is-waiting":""} ${denied?"is-denied":""}`}><Send/><b>Referral / Access request</b><small>{denied?"Denied · consent inactive":required?"Waiting for patient authorization":approved?"Authorized request":"Request prepared"}</small></motion.div><div className={`rc1-patient ${active>=2?"is-active":""}`}><span><UserRound/></span><b>Patient P</b><small>Controls consent</small><em className={approved?"is-approved":revoked?"is-revoked":"is-required"}>{approved?<CheckCircle2/>:<LockKeyhole/>}{approved?"Consent granted":revoked?"Consent revoked":"Authorization required"}</em></div><motion.div className={`rc1-retrieval ${active===4?"is-visible":""}`} initial={false} animate={{x:active===4&&!reduced?[0,160]:0}} transition={{duration:.55}}><KeyRound/>Secure view</motion.div><EvidenceRail title="Audit & Integrity" subtitle="Integrity commitments · audit history" label="Clinical data remains off-chain" count={evidenceCount} active={active>=5}/></motion.div>
}

export function StageToolbar({step,title,onReplay}:{step:number;title:string;onReplay:()=>void}){return <div className="narrative-stage-toolbar"><div><span>Step {String(step).padStart(2,"0")}</span><b>{title}</b></div><button type="button" onClick={onReplay}>Replay <RotateCcw/></button></div>}
function OrganizationCard({className,name,descriptor}:{className:string;name:string;descriptor:string}){return <article className={`narrative-organization ${className}`}><span><Hospital/></span><div><b>{name}</b><small>{descriptor}</small><em><i/>Online</em></div></article>}
export function EvidenceRail({title,subtitle,label,count,active}:{title:string;subtitle:string;label:string;count:number;active:boolean}){return <section className={`narrative-evidence-rail ${active?"is-active":""}`} aria-label={title}><header><span><Link2/></span><div><b>{title}</b><small>{subtitle}</small></div></header><div className="narrative-evidence-nodes">{[0,1,2,3,4].map(node=><i key={node} className={node<count?"is-recorded":""}><Database/></i>)}</div><p>Signed events <i/> Integrity commitments <i/> Audit history <i/> {label}</p></section>}
