import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render(path="/"){
  const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${process.pid}-${Date.now()}-${path}`);
  const{default:worker}=await import(workerUrl.href);
  return worker.fetch(new Request(`http://localhost${path}`,{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}});
}

for(const[path,content]of[["/","Secure health information exchange"],["/demo","Clinical record created"],["/app","Healthcare workspace"]])test(`renders ${path}`,async()=>{const response=await render(path);assert.equal(response.status,200);assert.match(await response.text(),new RegExp(content,"i"))});

for(const[path,content]of[["/app/patients","Patients"],["/app/referrals","Referrals"]])test(`direct reception route ${path} renders its section`,async()=>{const response=await render(path);assert.equal(response.status,200);assert.match(await response.text(),new RegExp(content,"i"))});

test("scroll story remains complete without animation",async()=>{const html=await(await render("/demo")).text();for(const phrase of["Data stays off-chain","Patient referred","requests access","Patient controls access","Consent granted","Authorized retrieval","Integrity verified","Every step is auditable"])assert.match(html,new RegExp(phrase,"i"))});

test("human workflows are driven by backend API boundaries",async()=>{const source=await readFile(new URL("../components/dashboard.tsx",import.meta.url),"utf8");for(const phrase of["careApi.register","careApi.checkIn","careApi.start","careApi.draft","careApi.complete","accessApi.request","consentApi.grant","clinicalApi.retrieve","clinicalApi.verifyShared"])assert.match(source,new RegExp(phrase.replace(".","\\."),"i"));assert.doesNotMatch(source,/useState<Flow>|setFlow/)});

test("sidebar navigation is role-specific",async()=>{const source=await readFile(new URL("../components/dashboard.tsx",import.meta.url),"utf8");assert.match(source,/role==="reception"\?\[\["Today","\/app"\],\["Patients","\/app\/patients"\],\["Referrals","\/app\/referrals"\]\]/);assert.doesNotMatch(source,/role==="reception"\?\[[^;]+\["Check-In"/);for(const label of["My Patients","Tasks","My Journey","Requests","My Records","Network Status"])assert.match(source,new RegExp(label));assert.match(source,/navFor\(role/);assert.match(source,/href=\{href\}/);assert.match(source,/usePathname/)});

test("reception today is queue-first and check-in remains an action",async()=>{const[source,reception]=await Promise.all([readFile(new URL("../components/dashboard.tsx",import.meta.url),"utf8"),readFile(new URL("../components/reception.tsx",import.meta.url),"utf8")]);for(const phrase of["Manage today&apos;s arrivals and patient queue","Check In Patient","Today's Patients","No patients have checked in yet","Regular visit","Referred from Hospital A","Reception patient view"])assert.ok((source+reception).includes(phrase),`missing ${phrase}`)});

test("reception patient search is debounced and backend authoritative",async()=>{const reception=await readFile(new URL("../components/reception.tsx",import.meta.url),"utf8");assert.match(reception,/careApi\.patients\("b", value\)/);assert.match(reception,/setTimeout\([^]*300/);assert.match(reception,/Searching patients/);assert.match(reception,/No matching patient found/);assert.match(reception,/Register New Patient/);assert.doesNotMatch(reception,/const\s+mock|fakePatient/i)});

test("reception check-in modal uses structured operational controls",async()=>{const reception=await readFile(new URL("../components/reception.tsx",import.meta.url),"utf8");for(const phrase of['role="dialog"','aria-modal="true"','What do you want to do?','Find Existing Patient','Register New Patient','name="gender"','Assigned doctor','Select a room','visitReasons','Please specify','Referral available','Use Referral','Continue as Regular Visit','Regular visit'])assert.match(reception,new RegExp(phrase));assert.doesNotMatch(reception,/<legend>Visit source/i);assert.match(reception,/event\.key === "Escape"/);assert.match(reception,/returnFocus\?\.focus/)});

test("successful check-in closes the modal and a fresh session always exposes registration",async()=>{const[dashboard,reception]=await Promise.all([readFile(new URL("../components/dashboard.tsx",import.meta.url),"utf8"),readFile(new URL("../components/reception.tsx",import.meta.url),"utf8")]);assert.match(reception,/if \(completed\) onSuccess\(selected, room\)/);assert.match(dashboard,/Patient checked in successfully/);assert.match(reception,/mode.*useState<"find" \| "register" \| null>/);assert.match(reception,/Register New Patient/)});

test("modal focus lifecycle is mount-only while escape uses the latest close callback",async()=>{const reception=await readFile(new URL("../components/reception.tsx",import.meta.url),"utf8");assert.match(reception,/const closeRef = useRef\(close\)/);assert.match(reception,/closeRef\.current = close/);assert.match(reception,/closeRef\.current\(\)/);assert.match(reception,/returnFocus\?\.focus\(\)/);assert.match(reception,/document\.addEventListener\("keydown", onKey\)[^]*\}, \[\]\)/)});

test("doctor home prioritizes current or earliest waiting patient",async()=>{const doctor=await readFile(new URL("../components/doctor.tsx",import.meta.url),"utf8");for(const phrase of["Current Visit","Next Patient","Up Next","Continue Visit","Start Visit","You&apos;re caught up.","currently in visit","waitingFor(primary.CheckedInAt)"])assert.match(doctor,new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(doctor,/sort\(byArrival\)/);assert.match(doctor,/active \? waiting : waiting\.slice\(1\)/)});

test("doctor patient directory is distinct and backend searchable",async()=>{const doctor=await readFile(new URL("../components/doctor.tsx",import.meta.url),"utf8");for(const phrase of["My Patients","Search patients by name, ID or phone","Today","Recent","All","View Patient","careApi.patients(\"b\", value)"])assert.ok(doctor.includes(phrase),`missing ${phrase}`);assert.match(doctor,/filter === "Today"/);assert.match(doctor,/filter === "Recent"/)});

test("doctor patient detail preserves clinical and external workflows",async()=>{const doctor=await readFile(new URL("../components/doctor.tsx",import.meta.url),"utf8");for(const phrase of["Patient Summary","Recent Visits","Local Records","External Records","Approval pending","Available securely","Request Access","View Record","This record remains stored at Hospital A.","Visit Documentation","Save Draft","Complete Visit","Treatment / Plan","Complete this visit?","Integrity protected · Verified"])assert.match(doctor,new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(doctor,/careApi\.start/);assert.match(doctor,/clinicalApi\.retrieve/);assert.match(doctor,/clinicalApi\.verifyShared/);assert.match(doctor,/visit\.ChiefComplaint \|\| visit\.Reason/);assert.match(doctor,/beforeunload/)});

test("doctor and patient pages own their context and Hospital B records load for every patient",async()=>{const dashboard=await readFile(new URL("../components/dashboard.tsx",import.meta.url),"utf8");assert.match(dashboard,/role!=="doctorB"&&!patientOwnsPage&&<div className="page-heading">/);assert.match(dashboard,/clinicalApi\.list\("b",""\)/)});

test("selects both hospitals by role and signs mutations with idempotency keys",async()=>{const[config,clinical,referrals,consent]=await Promise.all([readFile(new URL("../lib/config.ts",import.meta.url),"utf8"),readFile(new URL("../lib/api/clinical.ts",import.meta.url),"utf8"),readFile(new URL("../lib/api/referrals.ts",import.meta.url),"utf8"),readFile(new URL("../lib/api/consent.ts",import.meta.url),"utf8")]);assert.match(config,/doctorA.*hospital:"a"/);assert.match(config,/doctorB.*hospital:"b"/);for(const source of[clinical,referrals,consent])assert.match(source,/Idempotency-Key/)});

test("technical state is isolated to admin experience",async()=>{const source=await readFile(new URL("../components/dashboard.tsx",import.meta.url),"utf8");assert.match(source,/function Admin/);assert.match(source,/Technical audit/);assert.match(source,/Hospital network/)});

test("patient detail supports external viewing without copying and a new local visit record",async()=>{const source=await readFile(new URL("../components/dashboard.tsx",import.meta.url),"utf8");assert.match(source,/This record remains stored at Hospital A/);assert.match(source,/View External Record/);assert.match(source,/Complete Visit/);assert.match(source,/careApi\.complete/)});

test("patient home presents backend-authoritative normal and referred care journeys",async()=>{const[patient,dashboard,css]=await Promise.all([readFile(new URL("../components/patient-home.tsx",import.meta.url),"utf8"),readFile(new URL("../components/dashboard.tsx",import.meta.url),"utf8"),readFile(new URL("../app/patient-home.css",import.meta.url),"utf8")]);for(const phrase of["My Care Journey","Action required","Review request","Waiting for your doctor","Record access requested","Your approval","Record securely available","Access ended","Recent activity","Your original record stays here"])assert.match(patient,new RegExp(phrase,"i"));assert.doesNotMatch(patient,/patient-ownership-note/);assert.doesNotMatch(patient,/Secure access ended/);assert.match(patient,/data-kind=\{referred \? "referred" : "normal"\}/);assert.match(patient,/aria-current=\{stage\.status === "current" \? "step"/);assert.match(patient,/useReducedMotion/);assert.doesNotMatch(patient,/block hash|transaction id|private key/i);assert.match(dashboard,/clinicalApi\.list\("b",""\)/);assert.match(dashboard,/return <PatientRecords/);assert.match(css,/@media\s*\(max-width:\s*900px\)/)});

test("patient records is a verified hospital-owned clinical library",async()=>{const[records,dashboard,css]=await Promise.all([readFile(new URL("../components/patient-records.tsx",import.meta.url),"utf8"),readFile(new URL("../components/dashboard.tsx",import.meta.url),"utf8"),readFile(new URL("../app/patient-records.css",import.meta.url),"utf8")]);for(const phrase of["Your health records across your care network","Independent hospital records","Original records created at Hospital A","Records created during your care at Hospital B","View Record","Clinical Record","Integrity protected · Verified","Original record remains at Hospital A","records yet"])assert.match(records,new RegExp(phrase,"i"));assert.match(records,/clinicalApi\.verify/);assert.doesNotMatch(records,/repairArtifacts|repair-record-/);assert.match(records,/record\.PatientID === patientID && record\.OrganizationID === organization/);assert.match(records,/key=\{record\.ID\}/);assert.match(records,/role="list"/);assert.match(records,/useReducedMotion/);assert.match(dashboard,/path==="\/app\/records"/);assert.doesNotMatch(records,/transaction hash|block number|chain id|ledger id/i);assert.match(css,/@media\(max-width:430px\)/);assert.match(css,/prefers-reduced-motion:reduce/)});

test("patient requests uses human sections and real consent operations",async()=>{const[requests,dashboard,css]=await Promise.all([readFile(new URL("../components/patient-requests.tsx",import.meta.url),"utf8"),readFile(new URL("../components/dashboard.tsx",import.meta.url),"utf8"),readFile(new URL("../app/patient-requests.css",import.meta.url),"utf8")]);for(const phrase of["Needs Your Attention","Active Access","Past Requests","Review Request","Allow Access","Decline","Revoke Access","Request declined","Access approved","Access revoked","No active external access","Hospital B does not receive ownership","You can revoke access later"])assert.match(requests,new RegExp(phrase,"i"));for(const operation of["consentApi.grant","consentApi.decline","consentApi.revoke"])assert.ok(requests.includes(operation));assert.match(requests,/role="dialog"/);assert.match(requests,/aria-modal="true"/);assert.match(requests,/event\.key === "Escape"/);assert.match(requests,/returnFocus\?\.focus/);assert.match(requests,/useReducedMotion/);assert.match(dashboard,/return <PatientRequests/);assert.match(css,/@media\(max-width:600px\)/);assert.match(css,/prefers-reduced-motion:reduce/)});

test("maps backend errors to product language",async()=>{const source=await readFile(new URL("../lib/api/client.ts",import.meta.url),"utf8");for(const code of["consent_required","consent_revoked","replayed_request","operation_pending","integrity_failure"])assert.match(source,new RegExp(code))});

test("reduced motion preserves content and interaction",async()=>{const[story,dashboard,css]=await Promise.all([readFile(new URL("../components/demo-story.tsx",import.meta.url),"utf8"),readFile(new URL("../components/dashboard.tsx",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]);assert.match(story,/useReducedMotion/);assert.match(dashboard,/useReducedMotion/);assert.match(css,/prefers-reduced-motion:reduce/);assert.doesNotMatch(story,/pointerEvents:\s*["']none/)});

test("demo contains sticky scroll story and all visual stages",async()=>{const[story,css]=await Promise.all([readFile(new URL("../components/demo-story.tsx",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]);for(const feature of["useScroll","useTransform","whileInView","story-record","story-offchain","story-referral","story-request","story-consent","story-retrieval","story-integrity","story-audit"])assert.match(story,new RegExp(feature));assert.match(css,/story-canvas\{position:sticky/)});
