import type{Metadata}from"next";
import Image from"next/image";
import Link from"next/link";
import{ArrowDown,ArrowRight,Building2,CheckCircle2,Code2,Database,HeartPulse,Network,Search,ShieldCheck,UserRound}from"lucide-react";
const repo="https://github.com/sepehroveisi/healthtrust-exchange";
export const metadata:Metadata={title:"HealthTrust — Two healthcare trust prototypes",description:"HealthTrust's evolution from cross-hospital exchange to professional-authority evidence."};
const rc1=["Two independently operated hospital nodes","Referral and walk-in discovery paths","Patient-controlled consent and revocation","Off-chain records with SHA-256 commitments","Ed25519 signatures and replay protection","Custom permissioned blockchain"];
const rc2=["One professional-authority event","Three independently decided responses","PostgreSQL evidence held off-chain","Hyperledger Besu with three QBFT validators","Durable submission and reconciliation","Commitment-based integrity verification"];
const compare=[["Research question","Cross-hospital clinical access","Shared evidence without shared authority"],["Authority model","Patient-controlled authorization","Independent organization decisions"],["Sensitive data","Clinical records remain at source","Operational evidence remains local"],["Trust layer","Custom permissioned blockchain","Hyperledger Besu / QBFT"],["Demonstration","Referral, consent, access, revocation","Evidence, response, reconciliation, verification"]];
export default function Home(){return <main className="portfolio-page"><a className="portfolio-skip" href="#content">Skip to content</a><nav className="portfolio-nav" aria-label="Portfolio navigation"><Link href="/" className="portfolio-brand"><span><HeartPulse/></span><b>HealthTrust<small>Engineering portfolio</small></b></Link><div><a href="#evolution">Evolution</a><a href="#rc1">RC1</a><a href="#rc2">RC2</a><a href="#comparison">Comparison</a></div><a className="portfolio-github" href={repo} target="_blank" rel="noreferrer">GitHub <ArrowRight/></a></nav><div id="content">
<header className="portfolio-hero"><div><Overline>Healthcare trust · engineering research</Overline><h1>Two prototypes.<br/>One evolving question.</h1><p>HealthTrust explores where shared technical trust helps healthcare organizations—and where its complexity must be challenged. RC1 and RC2 are two first-class stages of that work.</p><div className="portfolio-actions"><Button href="/app">Explore RC1</Button><Button href="/authority" light>Explore RC2</Button></div></div><div className="portfolio-map" aria-label="HealthTrust evolution from RC1 through research to RC2"><Stage release="RC1" title="Cross-Hospital Exchange" note="Access and consent"/><span><i/><Search/><i/><small>Research</small></span><Stage release="RC2" title="Authority Response Ledger" note="Evidence and independence"/></div><a className="portfolio-scroll" href="#evolution"><ArrowDown/>Follow the evolution</a></header>
<section className="portfolio-section portfolio-evolution" id="evolution"><Heading label="Project evolution" title="The work advanced when the question changed.">RC1 created the practical experience needed to ask a narrower, more demanding question in RC2.</Heading><ol>{[["01","Build the exchange","Model records, referrals, patient authorization, and auditable access."],["02","Question the architecture","Ask why a distributed ledger belongs here instead of assuming that it does."],["03","Narrow the boundary","Focus on one event observed without shared operational authority."],["04","Test shared evidence","Keep local data and decisions while recording verifiable commitments."]].map(x=><li key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><p>{x[2]}</p></div></li>)}</ol></section>
<Prototype id="rc1" release="Release candidate 1" label="Cross-hospital exchange prototype" title="Patient-controlled access across two hospital nodes." intro="RC1 explores how Hospital B can request access to a Hospital A clinical record while Hospital A retains the source record and the patient controls cross-hospital authorization." details={rc1} primary="/portfolio/rc1-dashboard.png" secondary="/portfolio/rc1-consent.png" size={[1280,1083]} primaryAlt="RC1 Hospital B dashboard showing the cross-hospital care workflow" secondaryAlt="RC1 patient consent interface for a Hospital B access request"><Button href="/app">Open RC1 workspace</Button><TextLink href="/demo">View guided workflow</TextLink><TextLink href={`${repo}/blob/main/docs/rc1/README.md`} external>RC1 documentation</TextLink></Prototype>
<section className="portfolio-question"><div><Overline>The research transition</Overline><h2>Building RC1 raised a harder question:</h2><blockquote>Where does distributed trust actually justify its complexity?</blockquote></div><p>The next prototype moved away from simply expanding the exchange. It focused on cases where organizations need evidence about the same event, do not share operational authority, and must detect later inconsistency without surrendering independent decisions.</p></section>
<Prototype id="rc2" release="Release candidate 2" label="Professional authority response ledger" title="Shared evidence. Independent decisions." intro="RC2 demonstrates one synthetic professional-authority event observed by three organizations. Each validates shared evidence, then applies its own policy and records its own response." details={rc2} primary="/portfolio/rc2-operations.png" secondary="/portfolio/rc2-technical.png" size={[1440,1050]} primaryAlt="RC2 Operations view showing three independently completed organization responses" secondaryAlt="RC2 Technical view showing Besu validators and ledger submissions"><div className="portfolio-responses"><Response icon={<Building2/>} name="Hospital A">Scheduling disabled</Response><Response icon={<Database/>} name="Payer B">Enrollment and reimbursement held</Response><Response icon={<UserRound/>} name="Staffing Agency C">Assignment ended</Response></div><Button href="/authority">Open RC2 workspace</Button><TextLink href="/authority/demo">View RC2 story</TextLink><TextLink href={`${repo}/tree/main/docs/rc2`} external>RC2 documentation</TextLink></Prototype>
<section className="portfolio-section portfolio-integrity"><Heading label="Controlled integrity demonstration" title="Recorded evidence makes a later difference visible.">The blockchain does not prevent a PostgreSQL record from changing. Prior commitments make a later inconsistency detectable.</Heading><div className="portfolio-integrity-grid"><Screen src="/portfolio/rc2-integrity-mismatch.png" size={[1440,1050]} alt="Hospital A fails verification while Payer B and Staffing Agency C remain verified" caption="Controlled local change · recorded ledger evidence unchanged"/><div className="portfolio-states"><States title="Before"/><ArrowDown/><States title="After local change" failed/><p><ShieldCheck/>The comparison detects inconsistency relative to recorded evidence. It does not establish which value is true.</p></div></div></section>
<section className="portfolio-section portfolio-comparison" id="comparison"><Heading label="Two stages, one project" title="The prototypes answer different trust questions.">RC2 does not replace RC1. It narrows the question after the exchange exposed where architectural scrutiny mattered most.</Heading><div role="table"><div className="portfolio-table-head" role="row"><div role="columnheader">Dimension</div><div role="columnheader"><b>RC1 · Exchange</b></div><div role="columnheader"><b>RC2 · Evidence</b></div></div>{compare.map(x=><div className="portfolio-table-row" role="row" key={x[0]}><div role="cell"><span>{x[0]}</span></div><div role="cell"><p>{x[1]}</p></div><div role="cell"><p>{x[2]}</p></div></div>)}</div></section>
<section className="portfolio-section portfolio-engineering"><Heading label="Engineering depth" title="Built to test workflows and trust boundaries."/><div><Tech icon={<Network/>} label="RC1" title="Exchange system">Go · PostgreSQL · Ed25519 · SHA-256 · custom permissioned chain · React/TypeScript · Docker · Playwright</Tech><Tech icon={<Database/>} label="RC2" title="Evidence system">Go · PostgreSQL · Besu/QBFT · Solidity · SHA-256 · reconciliation · integrity verification · React/TypeScript</Tech><Tech icon={<Code2/>} label="Shared discipline" title="Explicit boundaries">Synthetic fixtures, off-chain sensitive data, durable state transitions, browser regression coverage, and documented non-claims.</Tech></div></section>
<aside className="portfolio-boundary"><ShieldCheck/><div><Overline>Project boundary</Overline><h2>An engineering and research portfolio.</h2></div><p>HealthTrust does not claim production readiness, regulatory compliance, practitioner or market validation, or that blockchain prevents source-system changes or makes source evidence true.</p></aside>
<section className="portfolio-final"><Overline>Explore the prototypes</Overline><h2>Choose the question you want to inspect.</h2><div><Choice href="/app" release="RC1" title="Cross-Hospital Exchange Prototype">Open the role-based healthcare workflow</Choice><Choice href="/authority" release="RC2" title="Professional Authority Response Ledger">Open the operations and technical workspace</Choice></div></section></div><footer className="portfolio-footer"><span>HealthTrust · engineering prototypes</span><a href={repo} target="_blank" rel="noreferrer">View source on GitHub</a></footer></main>}
function Overline({children}:{children:React.ReactNode}){return <span className="portfolio-overline">{children}</span>};
function Heading({label,title,children}:{label:string,title:string,children?:React.ReactNode}){return <div className="portfolio-heading"><Overline>{label}</Overline><h2>{title}</h2>{children&&<p>{children}</p>}</div>};
function Button({href,light,children}:{href:string;light?:boolean;children:React.ReactNode}){return <Link className={`portfolio-button ${light?"light":""}`} href={href}>{children}<ArrowRight/></Link>};
function TextLink({href,external,children}:{href:string;external?:boolean;children:React.ReactNode}){return <a className="portfolio-text-link" href={href} target={external?"_blank":undefined} rel={external?"noreferrer":undefined}>{children}<ArrowRight/></a>};
function Stage({release,title,note}:{release:string;title:string;note:string}){return <article><span>{release}</span><b>{title}</b><small>{note}</small></article>};
function Details({items}:{items:string[]}){return <ul>{items.map(x=><li key={x}><CheckCircle2/>{x}</li>)}</ul>};
function Response({icon,name,children}:{icon:React.ReactNode;name:string;children:React.ReactNode}){return <p>{icon}<span><b>{name}</b><small>{children}</small></span></p>};
function Screen({src,size,alt,caption,className=""}:{src:string;size:[number,number];alt:string;caption:string;className?:string}){return <figure className={`portfolio-screen ${className}`}><Image src={src} width={size[0]} height={size[1]} sizes="(max-width:800px) 92vw, 55vw" alt={alt}/><figcaption>{caption}</figcaption></figure>};
function Prototype(p:{id:string;release:string;label:string;title:string;intro:string;details:string[];primary:string;secondary:string;size:[number,number];primaryAlt:string;secondaryAlt:string;children:React.ReactNode}){return <section className={`portfolio-prototype ${p.id}`} id={p.id}><div><span className="portfolio-release">{p.release}</span><Overline>{p.label}</Overline><h2>{p.title}</h2><p className="portfolio-lead">{p.intro}</p>{p.id==="rc2"&&p.children}<Details items={p.details}/><div className="portfolio-actions">{p.id==="rc1"&&p.children}</div></div><div className="portfolio-screens"><Screen src={p.primary} size={p.size} alt={p.primaryAlt} caption={p.id==="rc1"?"Hospital workflow dashboard":"Operations view"} className="primary"/><Screen src={p.secondary} size={p.size} alt={p.secondaryAlt} caption={p.id==="rc1"?"Patient-controlled consent":"Technical evidence"} className="secondary"/></div></section>};
function States({title,failed}:{title:string;failed?:boolean}){return <div><span>{title}</span>{["Hospital A","Payer B","Staffing Agency C"].map((x,i)=><p key={x}><span>{x}</span><b className={failed&&i===0?"failed":"verified"}>{failed&&i===0?"Failed":"Verified"}</b></p>)}</div>};
function Tech({icon,label,title,children}:{icon:React.ReactNode;label:string;title:string;children:React.ReactNode}){return <article>{icon}<span>{label}</span><h3>{title}</h3><p>{children}</p></article>};
function Choice({href,release,title,children}:{href:string;release:string;title:string;children:React.ReactNode}){return <Link href={href}><span>{release}</span><b>{title}</b><small>{children}</small><ArrowRight/></Link>};
