import Link from "next/link";
import { ArrowRight, CheckCircle2, Database, HeartPulse, ShieldCheck } from "lucide-react";

export default function Home() {
  return <main>
    <nav className="nav"><Link href="/" className="brand"><span className="brand-mark"><HeartPulse size={20}/></span>HealthTrust <b>Exchange</b></Link><div className="nav-links"><Link href="/demo">How it works</Link><Link href="/app">Interactive demo</Link></div><Link href="/app" className="button small">Open dashboard <ArrowRight size={16}/></Link></nav>
    <section className="hero">
      <div className="hero-copy"><span className="eyebrow"><ShieldCheck size={15}/> Patient-controlled health exchange</span><h1>Secure health information exchange built around <em>trusted access.</em></h1><p>Clinical records remain off-chain while a permissioned trust layer provides verifiable integrity, authorization, and auditability across healthcare organizations.</p><div className="actions"><Link href="/demo" className="button">Explore the workflow <ArrowRight size={17}/></Link><Link href="/app" className="button secondary">Open demo dashboard</Link></div><div className="trust-row"><span><CheckCircle2/>Patient consent</span><span><CheckCircle2/>Off-chain records</span><span><CheckCircle2/>Verified audit</span></div></div>
      <div className="hero-visual" aria-label="Hospital A and Hospital B connected through patient-controlled trust"><div className="orb orb-a"/><div className="orb orb-b"/><div className="hospital-card hospital-a"><span className="hospital-icon">A</span><div><b>Hospital A</b><small>Source organization</small></div><span className="online">Online</span></div><div className="patient-card"><div className="avatar">PP</div><div><b>Patient P</b><small>Consent active</small></div><ShieldCheck size={22}/></div><div className="secure-path"><span/><div><ShieldCheck size={18}/> Authorized path</div><span/></div><div className="hospital-card hospital-b"><span className="hospital-icon">B</span><div><b>Hospital B</b><small>Receiving organization</small></div><span className="online">Online</span></div><div className="commit-card"><Database size={19}/><div><b>Integrity commitment</b><small>Clinical data stays off-chain</small></div><CheckCircle2 size={20}/></div></div>
    </section>
    <section className="principles"><article><span>01</span><h3>Clinical by design</h3><p>Calm, role-specific experiences keep sensitive work clear and efficient.</p></article><article><span>02</span><h3>Consent is operational</h3><p>Access remains locked until the patient grants an exact, verifiable permission.</p></article><article><span>03</span><h3>Trust you can inspect</h3><p>Every commitment, referral, consent, access, and revocation is auditable.</p></article></section>
  </main>
}
