import { expect, type Page, test } from "@playwright/test";

const referralSuffix = Date.now().toString(36);
const referralPatient = { name: `Referral Patient ${referralSuffix}`, network: `referral-network-${referralSuffix}`, localA: `referral-a-${referralSuffix}`, localB: `referral-patient-${referralSuffix}` };

test("registration controls preserve focus during realistic typing and editing", async ({ page }) => {
  await page.goto("/app");
  const trigger = page.getByRole("button", { name: "Check In Patient" }).first();
  await trigger.click();
  const modal = page.getByRole("dialog", { name: "Check In Patient" });
  await modal.getByRole("button", { name: "Register New Patient" }).click();
  const registration = modal.getByTestId("patient-registration");
  const name = registration.getByLabel("Full Name");
  await name.click();
  await name.pressSequentially("Sarah Johnson", { delay: 275 });
  await expect(name).toBeFocused();
  await expect(name).toHaveValue("Sarah Johnson");
  await name.press("ArrowLeft");
  await name.press("Backspace");
  await name.pressSequentially("o");
  await expect(name).toBeFocused();
  await expect(name).toHaveValue("Sarah Johnson");
  const dob = registration.getByLabel("Date of Birth");
  await dob.fill("1992-06-14");
  await expect(dob).toBeFocused();
  await registration.getByLabel("Female", { exact: true }).check();
  await expect(registration.getByLabel("Female", { exact: true })).toBeFocused();
  const phone = registration.getByLabel("Phone");
  await phone.click();
  await phone.pressSequentially("09121234567", { delay: 100 });
  await expect(phone).toBeFocused();
  await expect(phone).toHaveValue("09121234567");
  await phone.press("ArrowLeft");
  await phone.press("Backspace");
  await phone.pressSequentially("6");
  await expect(phone).toHaveValue("09121234567");
  await registration.getByRole("button", { name: "Register and Continue" }).click();
  await modal.getByLabel("Room").selectOption("203");
  await modal.getByLabel("Visit reason").selectOption("Other");
  const other = modal.getByLabel("Please specify");
  await other.click();
  await other.pressSequentially("Travel consultation", { delay: 50 });
  await expect(other).toBeFocused();
  await expect(other).toHaveValue("Travel consultation");
  await page.keyboard.press("Escape");
  await expect(modal).toBeHidden();
  await expect(trigger).toBeFocused();
  await trigger.click();
  const reopened = page.getByRole("dialog", { name: "Check In Patient" });
  await reopened.getByRole("button", { name: "Find Existing Patient" }).click();
  const search = reopened.getByPlaceholder("Search patient by name, ID or phone...");
  await search.click();
  await search.pressSequentially("Sarah", { delay: 100 });
  await expect(search).toBeFocused();
  await expect(search).toHaveValue("Sarah");
  await page.keyboard.press("Escape");
});

async function registerAndCheckIn(page: Page, patient: { id: string; name: string; room: string; reason: string }) {
  await page.getByRole("button", { name: "Check In Patient" }).first().click();
  const modal = page.getByRole("dialog", { name: "Check In Patient" });
  await expect(modal).toBeVisible();
  await expect(modal.getByRole("button", { name: "Register New Patient" })).toBeVisible();
  await modal.getByRole("button", { name: "Register New Patient" }).click();
  const registration = modal.getByTestId("patient-registration");
  await registration.getByLabel("Full name").fill(patient.name);
  await registration.getByLabel("Date of birth").fill("1990-02-03");
  await registration.getByLabel("Female", { exact: true }).check();
  await registration.getByLabel("Phone").fill(`555-${patient.id.slice(-4).padStart(4, "0")}`);
  await registration.getByRole("button", { name: "Register and Continue" }).click();
  await expect(modal.getByText("Patient selected")).toBeVisible();
  await modal.getByLabel("Assigned doctor").selectOption("doctor-b");
  await modal.getByLabel("Room").selectOption(patient.room);
  await modal.getByLabel("Visit reason").selectOption(patient.reason);
  await expect(modal.getByText("Regular visit")).toBeVisible();
  await expect(modal.getByText("Visit source")).toHaveCount(0);
  await modal.getByRole("button", { name: "Check In Patient" }).click();
  await expect(modal).toBeHidden();
  await expect(page.getByText("Patient checked in successfully")).toBeVisible();
  const row = page.locator(".queue-row").filter({ hasText: patient.name });
  await expect(row).toContainText(patient.reason);
  await expect(row).toContainText(`Room ${patient.room}`);
  await expect(row).toContainText("Regular visit");
}

test("reception checks in three independent patients and persistence survives refresh", async ({ page }) => {
  await page.goto("/app");
  await expect(page.getByRole("link", { name: "Check-In" })).toHaveCount(0);
  await registerAndCheckIn(page, { id: "patient-a", name: "Patient A", room: "203", reason: "General consultation" });
  await registerAndCheckIn(page, { id: "patient-b", name: "Patient B", room: "204", reason: "Follow-up" });
  await registerAndCheckIn(page, { id: "patient-c", name: "Patient C", room: "205", reason: "New symptoms" });
  for (const name of ["Patient A", "Patient B", "Patient C"]) await expect(page.locator(".queue-row").filter({ hasText: name })).toBeVisible();
  await page.reload();
  for (const [name, room] of [["Patient A", "203"], ["Patient B", "204"], ["Patient C", "205"]]) {
    const row = page.locator(".queue-row").filter({ hasText: name });
    await expect(row).toBeVisible();
    await expect(row).toContainText(`Room ${room}`);
  }
});

test("doctor home, patient detail, current visit, and directory use authoritative state", async ({ page }) => {
  await page.goto("/app");
  await page.getByTestId("role-switcher").selectOption("doctorB");
  await page.getByRole("link", { name: "My Patients" }).click();
  const initialDirectory = page.locator(".patient-directory");
  await initialDirectory.getByPlaceholder("Search patients by name, ID or phone...").fill("Patient A");
  await initialDirectory.locator("article").filter({ hasText: "Patient A" }).getByRole("button", { name: "View Patient" }).click();
  const detail = page.locator(".doctor-patient-detail");
  await expect(detail).toContainText("Patient A");
  await expect(detail.locator(".today-visit")).toContainText("General consultation");
  await expect(detail.locator(".today-visit")).toContainText("Room 203");
  await expect(detail.locator(".today-visit")).toContainText("Waiting");
  await detail.getByTestId("start-visit").click();
  await expect(detail.locator(".visit-progress")).toContainText("Visit in progress");
  await expect(detail.getByTestId("visit-documentation")).toBeVisible();
  await page.getByRole("link", { name: "Home", exact: true }).click();
  await expect(page.locator(".doctor-primary")).toContainText("Current Visit");
  await expect(page.locator(".doctor-primary")).toContainText("Patient A");
  await expect(page.locator(".doctor-primary").getByRole("button", { name: "Continue Visit" })).toBeVisible();
  await page.reload();
  await expect(page.locator(".doctor-primary")).toContainText("Current Visit");
  await page.locator(".doctor-primary").getByRole("button", { name: "Continue Visit" }).click();
  await page.locator(".doctor-patient-detail").getByRole("button", { name: "Continue Visit" }).click();
  const documentation = page.getByTestId("visit-documentation");
  await expect(documentation.getByLabel("Chief Complaint")).toHaveValue("General consultation");
  await documentation.getByLabel("Chief complaint").fill("Routine review");
  await documentation.getByLabel("Clinical notes").fill("Patient examined at Hospital B");
  await documentation.getByLabel("Diagnosis").fill("Wellness examination");
  await documentation.getByLabel("Treatment / Plan").fill("Return as needed");
  await documentation.getByLabel("Prescription / Medication").fill("No prescription");
  await documentation.getByRole("button", { name: "Save Draft" }).click();
  await expect(documentation.getByText("Draft saved")).toBeVisible();
  await page.reload();
  await expect(page.locator(".doctor-primary")).toContainText("Current Visit");
  await page.locator(".doctor-primary").getByRole("button", { name: "Continue Visit" }).click();
  await page.locator(".doctor-patient-detail").getByRole("button", { name: "Continue Visit" }).click();
  const recovered = page.getByTestId("visit-documentation");
  await expect(recovered.getByLabel("Chief Complaint")).toHaveValue("Routine review");
  await expect(recovered.getByLabel("Clinical Notes")).toHaveValue("Patient examined at Hospital B");
  await expect(recovered.getByLabel("Diagnosis")).toHaveValue("Wellness examination");
  await expect(recovered.getByLabel("Treatment / Plan")).toHaveValue("Return as needed");
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator(".visit-workspace").evaluate(element => element.scrollWidth <= element.clientWidth)).resolves.toBe(true);
  await expect(recovered.getByRole("button", { name: "Save Draft" })).toBeVisible();
  await expect(recovered.getByRole("button", { name: "Complete Visit" })).toBeVisible();
  const notes = recovered.getByLabel("Clinical Notes");
  await notes.fill("Patient examined at Hospital B; ");
  await notes.pressSequentially("final review complete", { delay: 175 });
  await expect(notes).toBeFocused();
  await expect(notes).toHaveValue("Patient examined at Hospital B; final review complete");
  await recovered.getByTestId("complete-visit").click();
  const confirmation = page.getByRole("dialog", { name: "Complete this visit?" });
  await expect(confirmation).toBeVisible();
  await expect(confirmation.getByRole("button", { name: "Cancel" })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(confirmation).toBeHidden();
  await recovered.getByTestId("complete-visit").click();
  await confirmation.getByRole("button", { name: "Complete Visit" }).click();
  const record = page.getByTestId("local-record");
  await expect(record).toContainText("Hospital B");
  await expect(record).toContainText("Routine review");
  await expect(record).toContainText("final review complete");
  await expect(record).toContainText("Wellness examination");
  await expect(record).toContainText("Return as needed");
  await expect(record).toContainText("Integrity protected · Verified");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("link", { name: "Home", exact: true }).click();
  await expect(page.locator(".doctor-primary")).not.toContainText("Patient A");
  await expect(page.locator(".completed-note")).toContainText("completed today");
  await page.getByRole("link", { name: "My Patients" }).click();
  const directory = page.locator(".patient-directory");
  await expect(directory.getByRole("heading", { name: "My Patients" })).toBeVisible();
  await expect(directory.locator(".doctor-primary")).toHaveCount(0);
  await expect(directory.getByRole("button", { name: "Today" })).toBeVisible();
  await expect(directory.getByRole("button", { name: "Recent" })).toBeVisible();
  await expect(directory.getByRole("button", { name: "All" })).toBeVisible();
  const search = directory.getByPlaceholder("Search patients by name, ID or phone...");
  await search.pressSequentially("Patient B", { delay: 50 });
  const patientB = directory.locator(".patient-directory-list article").filter({ hasText: "Patient B" });
  await expect(patientB).toBeVisible();
  await patientB.getByRole("button", { name: "View Patient" }).click();
  await expect(page.locator(".doctor-patient-detail")).toContainText("Patient B");
  await expect(page.locator(".doctor-patient-detail")).toContainText("Patient Summary");
  await expect(page.locator(".doctor-patient-detail")).toContainText("Recent Visits");
});

test("reception finds and checks in an existing patient", async ({ page }) => {
  await page.goto("/app");
  await page.getByRole("button", { name: "Check In Patient" }).first().click();
  const modal = page.getByRole("dialog", { name: "Check In Patient" });
  await modal.getByRole("button", { name: "Find Existing Patient" }).click();
  await modal.getByPlaceholder("Search patient by name, ID or phone...").fill("Patient A");
  await modal.getByRole("button", { name: "Select Patient" }).click();
  await modal.getByLabel("Room").selectOption("203");
  await modal.getByLabel("Visit reason").selectOption("Test / results review");
  await modal.getByRole("button", { name: "Check In Patient" }).click();
  await expect(modal).toBeHidden();
  await expect(page.locator(".queue-row").filter({ hasText: "Patient A" })).toHaveCount(2);
});

test("reception uses a real incoming referral without technical identifiers", async ({ page }) => {
  test.setTimeout(60_000);
  expect((await page.request.post("http://127.0.0.1:8081/patients", { data: { ID: referralPatient.localA, NetworkPatientID: referralPatient.network, FullName: referralPatient.name, DateOfBirth: "1984-08-12", Gender: "Male", Phone: "555-0101" } })).ok()).toBe(true);
  await page.goto("/app");
  await page.getByTestId("role-switcher").selectOption("doctorA");
  await page.getByPlaceholder("Search patients by name, ID or phone...").fill(referralPatient.name);
  await page.locator(".patient-directory-list article").filter({ hasText: referralPatient.name }).getByRole("button", { name: "View Patient" }).click();
  await page.getByTestId("source-visit").getByRole("button", { name: "Complete Visit" }).click();
  await page.getByTestId("create-referral").click();
  await page.getByTestId("role-switcher").selectOption("reception");
  await page.getByRole("button", { name: "Check In Patient" }).first().click();
  const drawer = page.getByRole("dialog", { name: "Check In Patient" });
  await drawer.getByRole("button", { name: "Register New Patient" }).click();
  const registration = drawer.getByTestId("patient-registration");
  await registration.getByLabel("Full name").fill(referralPatient.name);
  await registration.getByLabel("Date of birth").fill("1984-08-12");
  await registration.getByLabel("Male", { exact: true }).check();
  await registration.getByLabel("Phone").fill("555-0101");
  await registration.getByLabel("Existing care network ID").fill(referralPatient.network);
  await registration.getByRole("button", { name: "Register and Continue" }).click();
  await expect(drawer.getByText("Referral available")).toBeVisible();
  await expect(drawer.getByText("Hospital A → Hospital B")).toBeVisible();
  await expect(drawer.getByText("Referral ID")).toHaveCount(0);
  await drawer.getByRole("button", { name: "Use Referral" }).click();
  await drawer.getByLabel("Room").selectOption("203");
  await drawer.getByLabel("Visit reason").selectOption("Post-treatment follow-up");
  await drawer.getByRole("button", { name: "Check In Patient" }).click();
  await expect(drawer).toBeHidden();
  await expect(page.locator(".queue-row").filter({ hasText: referralPatient.name })).toContainText("Referred from Hospital A");
  await page.getByTestId("role-switcher").selectOption("doctorB");
  await page.getByRole("link", { name: "My Patients" }).click();
  let directory = page.locator(".patient-directory");
  await directory.getByPlaceholder("Search patients by name, ID or phone...").fill(referralPatient.name);
  await directory.locator("article").filter({ hasText: referralPatient.name }).getByRole("button", { name: "View Patient" }).click();
  let detail = page.locator(".doctor-patient-detail");
  await expect(detail.getByText("External Records")).toBeVisible();
  await expect(detail).toContainText("External record access requires patient approval");
  await detail.getByTestId("request-access").click();
  await expect(detail).toContainText("Approval pending");
  await page.getByTestId("role-switcher").selectOption("patient");
  await page.getByTestId("patient-switcher").selectOption(referralPatient.localB);
  await page.getByRole("link", { name: "Home", exact: true }).click();
  const patientHome = page.locator(".patient-home");
  await expect(patientHome.locator(".patient-action-required")).toContainText("Dr. B is requesting access");
  await expect(patientHome.getByTestId("patient-care-journey")).toHaveAttribute("data-kind", "referred");
  await expect(patientHome.getByTestId("patient-care-journey")).toContainText("Your approval");
  await patientHome.getByRole("link", { name: "Review request" }).click();
  await expect(page.getByRole("heading", { name: "Needs Your Attention" })).toBeVisible();
  await expect(page.locator(".patient-request-card")).toContainText("Waiting for your decision");
  await page.getByRole("button", { name: "Review Request" }).click();
  const review = page.getByRole("dialog", { name: "Dr. B at Hospital B is requesting access" });
  await expect(review).toContainText("Hospital A clinical record");
  await expect(review).toContainText("Continuity of care");
  await expect(review).toContainText("does not receive ownership");
  await page.getByTestId("allow-access").click();
  await expect(page.getByText("Access approved", { exact: true }).first()).toBeVisible();
  await expect(page.getByRole("heading", { name: "Active Access" }).locator(".." )).toContainText("Access you have currently approved");
  await page.getByRole("link", { name: "Home", exact: true }).click();
  await expect(page.getByTestId("patient-care-journey")).toContainText("Record securely available");
  await expect(page.locator(".record-location")).toContainText("Your original record stays here");
  await page.getByTestId("role-switcher").selectOption("doctorB");
  await page.getByRole("link", { name: "My Patients" }).click();
  directory = page.locator(".patient-directory");
  await directory.getByPlaceholder("Search patients by name, ID or phone...").fill(referralPatient.name);
  await directory.locator("article").filter({ hasText: referralPatient.name }).getByRole("button", { name: "View Patient" }).click();
  detail = page.locator(".doctor-patient-detail");
  await expect(detail).toContainText("Available securely");
  await detail.getByTestId("open-external-record").click();
  await expect(detail.getByTestId("external-record")).toContainText("Integrity verified");
  await expect(detail.getByTestId("external-record")).toContainText("This record remains stored at Hospital A.");
});

test("referred visit completion and revocation remain authoritative", async ({ page }) => {
  await page.goto("/app");
  await page.getByTestId("role-switcher").selectOption("doctorB");
  await page.getByRole("link", { name: "My Patients" }).click();
  let directory = page.locator(".patient-directory");
  await directory.getByPlaceholder("Search patients by name, ID or phone...").fill(referralPatient.name);
  await directory.locator("article").filter({ hasText: referralPatient.name }).getByRole("button", { name: "View Patient" }).click();
  const detail = page.locator(".doctor-patient-detail");
  await detail.getByTestId("start-visit").click();
  const documentation = detail.getByTestId("visit-documentation");
  await documentation.getByLabel("Chief complaint").fill("Blood pressure follow-up");
  await documentation.getByLabel("Clinical notes").fill("Patient examined at Hospital B");
  await documentation.getByLabel("Diagnosis").fill("Controlled hypertension");
  await documentation.getByLabel("Treatment / Plan").fill("Review in four weeks");
  await documentation.getByLabel("Prescription / Medication").fill("Continue medication");
  await documentation.getByTestId("complete-visit").click();
  await page.getByRole("dialog", { name: "Complete this visit?" }).getByRole("button", { name: "Complete Visit" }).click();
  await expect(page.getByTestId("local-record")).toContainText("Hospital B");
  const [sourceResponse, localResponse] = await Promise.all([
    page.request.get(`http://127.0.0.1:8081/clinical-records?patientId=${referralPatient.localA}`),
    page.request.get(`http://127.0.0.1:8082/clinical-records?patientId=${referralPatient.localB}`),
  ]);
  expect(sourceResponse.ok()).toBe(true);
  expect(localResponse.ok()).toBe(true);
  const sourceRecords = await sourceResponse.json() as Array<{ ID: string; OrganizationID: string; EncounterSummary: string; Diagnosis: string; Prescription: string }>;
  const localRecords = await localResponse.json() as Array<{ ID: string; OrganizationID: string; EncounterSummary: string; Diagnosis: string; Prescription: string }>;
  expect(sourceRecords.some(record => record.OrganizationID === "hospital-a")).toBe(true);
  expect(localRecords.some(record => record.OrganizationID === "hospital-b")).toBe(true);
  expect(localRecords.some(local => sourceRecords.some(source => source.ID === local.ID))).toBe(false);
  expect(localRecords.some(local => sourceRecords.some(source => `${source.EncounterSummary}|${source.Diagnosis}|${source.Prescription}` === `${local.EncounterSummary}|${local.Diagnosis}|${local.Prescription}`))).toBe(false);
  await page.getByTestId("role-switcher").selectOption("patient");
  await page.getByTestId("patient-switcher").selectOption(referralPatient.localB);
  await page.getByRole("link", { name: "Home", exact: true }).click();
  await expect(page.getByTestId("patient-care-journey")).toContainText("Visit completed");
  await expect(page.locator(".patient-recent")).toContainText("Hospital B record available");
  await expect(page.locator(".record-location")).toContainText("Your original record stays here");
  await page.getByRole("link", { name: "My Records" }).click();
  const patientRecords = page.locator(".patient-records");
  await expect(patientRecords.locator('[data-hospital="a"] .patient-record-card')).toHaveCount(1);
  await expect(patientRecords.locator('[data-hospital="b"] .patient-record-card')).toHaveCount(1);
  await expect(patientRecords).not.toContainText("Verified referral context");
  await expect(patientRecords.locator('[data-hospital="a"]')).toContainText("Essential hypertension");
  await expect(patientRecords.locator('[data-hospital="b"]')).toContainText("Controlled hypertension");
  await patientRecords.locator('[data-hospital="a"]').getByRole("button", { name: "View Record" }).click();
  await expect(page.getByTestId("patient-record-detail")).toContainText("Your original record remains at Hospital A");
  await page.getByRole("button", { name: "Back to My Records" }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator(".patient-records").evaluate(element => element.scrollWidth <= element.clientWidth)).resolves.toBe(true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("link", { name: "Requests" }).click();
  await page.getByRole("button", { name: "Revoke Access" }).click();
  const revoke = page.getByRole("dialog", { name: "Revoke Dr. B's access?" });
  await expect(revoke).toContainText("does not delete");
  await expect(revoke.getByRole("button", { name: "Cancel" })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(revoke).toBeHidden();
  await page.getByRole("button", { name: "Revoke Access" }).click();
  await page.getByTestId("confirm-revoke-access").click();
  await expect(page.getByText("Access revoked", { exact: true }).first()).toBeVisible();
  await expect(page.getByRole("heading", { name: "Past Requests" }).locator(".." )).toContainText("Requests that are no longer active");
  await page.getByRole("link", { name: "Home", exact: true }).click();
  await expect(page.locator(".patient-recent")).toContainText("Access revoked");
  await expect(page.getByTestId("patient-care-journey")).toContainText("Access ended");
  await expect(page.getByTestId("patient-care-journey")).not.toContainText("Secure access ended");
  await page.getByTestId("role-switcher").selectOption("doctorB");
  await page.getByRole("link", { name: "My Patients" }).click();
  directory = page.locator(".patient-directory");
  await directory.getByPlaceholder("Search patients by name, ID or phone...").fill(referralPatient.name);
  await directory.locator("article").filter({ hasText: referralPatient.name }).getByRole("button", { name: "View Patient" }).click();
  await expect(page.locator(".doctor-patient-detail")).toContainText("Access revoked");
});

test("modal supports conditional other reason, escape, and mobile layout", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/app");
  const trigger = page.getByRole("button", { name: "Check In Patient" }).first();
  await trigger.click();
  const drawer = page.getByRole("dialog", { name: "Check In Patient" });
  await expect(drawer).toBeVisible();
  await expect(drawer.evaluate(element => element.scrollWidth <= element.clientWidth)).resolves.toBe(true);
  await drawer.getByRole("button", { name: "Find Existing Patient" }).click();
  await drawer.getByPlaceholder("Search patient by name, ID or phone...").fill("Patient A");
  await drawer.getByRole("button", { name: "Select Patient" }).click();
  await drawer.getByLabel("Visit reason").selectOption("Other");
  await expect(drawer.getByLabel("Please specify")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(drawer).toBeHidden();
  await expect(trigger).toBeFocused();
});
